### ISSUE TITLE
File nesting does not appear to work for Shared Project type

### ISSUE THREAD

**Issue by djohnst10** [madskristensen/FileNesting#62] opened 2016-10-24 21:05 UTC
### Installed product versions
- Visual Studio: Visual Studio Professional 2015
- This extension: 2.5.63

### Description
Nesting items in a Shared project type does not appear to work.

### Steps to recreate
1. Create an Visual Studio solution.
2. Add a C# class library and C# Shared project to the solution.
3. Add the files TextFile1.txt and TextFile1.nested.txt to both projects.
4. Right click the TextFile1.nested.txt in the class library project and select Nest file. Select the file TextFile1.txt. The TextFile1.nested.txt file is nested under the TextFile1.txt file.
5. Right click the TextFile1.nested.txt in the shared project and select Nest file. Select the file TextFile1.txt. The TextFile1.nested.txt file is **not** nested under the TextFile1.txt file.

### Current behavior
In a Shared project, you cannot nest files with the extension.

### Expected behavior
In a Shared project, you can nest files with the extension.

Related issue: madskristensen/markdowneditor#69

**Comment by madskristensen** [comment] 2016-10-24 21:10
Dupe of #40

**Closed by madskristensen** 2016-10-24 21:10 UTC
