### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by acostaf** [madskristensen/FileNesting#58] opened 2016-05-17 14:09 UTC
### Installed product versions
- Visual Studio: 2013 Premium
- This extension: 2.4.58

### Description
Does not work anymore

### Steps to recreate
1. Install it
2. Select three files (.Ts, .Js and map)
3. click on Nest 
4. Nothing happends

### Current behavior
This is not longer working on Visual studio 2013, does nothing automatically or manually.

### Expected behavior
Nest Files

**Comment by tomascassidy** [comment] 2016-05-19 06:28
Could be a duplicate of #56. Does the [workaround](https://github.com/madskristensen/FileNesting/issues/56#issuecomment-212354748) work for you?

**Comment by acostaf** [comment] 2016-05-19 09:00
Thanks @tomascassidy that worked

**Closed** 2016-05-19 16:27 UTC
